import path from "node:path";
import type { SpecModel } from "../models.js";
import { toJsonStable, writeTextFile } from "../util.js";

const audioConfig = {
  noiseSuppression: { enabled: true, level: 1 },
  echoCancellation: { enabled: true, nlpLevel: 1 }
};

const audioCapabilities = {
  capability: "audio.algorithm",
  updatePolicy: {
    partialUpdateSupported: true,
    multiAlgorithmUpdateSupported: true,
    atomicUpdateSupported: true
  },
  algorithms: {
    noiseSuppression: {
      supported: true,
      enabled: { type: "boolean", defaultBoolean: true },
      level: { type: "uint8", min: 0, max: 5, step: 1, defaultUInt8: 1 }
    },
    echoCancellation: {
      supported: true,
      enabled: { type: "boolean", defaultBoolean: true },
      nlpLevel: { type: "uint8", min: 0, max: 3, step: 1, defaultUInt8: 1 }
    }
  }
};

export async function emitMockServerFiles(spec: SpecModel, generatedDir: string): Promise<void> {
  await Promise.all([
    emitSharedFixtures(spec, path.join(generatedDir, "shared")),
    emitNodeMockServer(path.join(generatedDir, "node-mock-server")),
    emitCppMockServer(path.join(generatedDir, "cpp-mock-server"))
  ]);
}

async function emitSharedFixtures(spec: SpecModel, dir: string): Promise<void> {
  const audioMethods = spec.methods
    .filter((method) => method.domain === "audio")
    .sort((lhs, rhs) => lhs.id - rhs.id)
    .map((method) => ({
      id: method.id,
      name: method.name,
      requestSchema: method.requestSchema,
      responseSchema: method.responseSchema
    }));
  await Promise.all([
    writeTextFile(path.join(dir, "audio-scenario.json"), toJsonStable({
      name: "audio-default",
      description: "Default AXTP audio mock responses for client-side protocol testing.",
      methods: {
        "audio.getAlgorithmConfig": { response: audioConfig },
        "audio.getAlgorithmCapabilities": { response: audioCapabilities },
        "audio.setAlgorithmConfig": {
          response: {
            applyState: "applied",
            requiresAudioRestart: false,
            config: audioConfig
          }
        }
      }
    })),
    writeTextFile(path.join(dir, "audio-registry.json"), toJsonStable({ methods: audioMethods }))
  ]);
}

async function emitNodeMockServer(dir: string): Promise<void> {
  await Promise.all([
    writeTextFile(path.join(dir, "package.json"), `{
  "name": "@axtp/generated-node-mock-server",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "smoke": "node dist/smoke.js",
    "test": "node dist/smoke.js"
  },
  "dependencies": {
    "@axtp/runtime": "link:../../../axtp-ts-runtime"
  },
  "devDependencies": {
    "@types/node": "^22.10.2",
    "typescript": "^5.7.2"
  },
  "packageManager": "pnpm@11.3.0"
}
`),
    writeTextFile(path.join(dir, "tsconfig.json"), `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`),
    writeTextFile(path.join(dir, "README.md"), `# Generated AXTP Node Mock Scenario Harness

This generated project uses \`@axtp/runtime\` from the sibling
\`axtp-ts-runtime\` repository. It runs a TCP AXTP Standard Framed mock
server on the Node.js backend.

\`\`\`bash
pnpm install
pnpm build
pnpm smoke
\`\`\`

By default the server listens on \`127.0.0.1:50362\`. Override with
\`AXTP_MOCK_TCP_HOST\` and \`AXTP_MOCK_TCP_PORT\`.

The default handlers cover \`audio.getAlgorithmConfig\`,
\`audio.getAlgorithmCapabilities\`, and \`audio.setAlgorithmConfig\`.
`),
    writeTextFile(path.join(dir, "src/audioHandlers.ts"), nodeAudioHandlers()),
    writeTextFile(path.join(dir, "src/main.ts"), nodeMain()),
    writeTextFile(path.join(dir, "src/smoke.ts"), nodeSmoke())
  ]);
}

function nodeAudioHandlers(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
import type { AxtpServer } from "@axtp/runtime";

const defaultConfig = {
  noiseSuppression: { enabled: true, level: 1 },
  echoCancellation: { enabled: true, nlpLevel: 1 }
};

const capabilities = ${JSON.stringify(audioCapabilities, null, 2)};

export class AudioMockState {
  private config = structuredClone(defaultConfig);

  install(server: AxtpServer): void {
    server.handleRaw("audio.getAlgorithmConfig", async () => structuredClone(this.config));
    server.handleRaw("audio.getAlgorithmCapabilities", async () => structuredClone(capabilities));
    server.handleRaw("audio.setAlgorithmConfig", async (_context, params) => {
      const parsed = typeof params === "object" && params !== null ? params : {};
      const record = parsed as Record<string, unknown>;
      const patch = typeof record.config === "object" && record.config !== null
        ? record.config
        : parsed;
      this.mergeConfig(patch);
      return {
        applyState: "applied",
        requiresAudioRestart: false,
        config: structuredClone(this.config)
      };
    });
  }

  private mergeConfig(patch: unknown): void {
    if (typeof patch !== "object" || patch === null) return;
    for (const [algorithm, value] of Object.entries(patch as Record<string, unknown>)) {
      if (typeof value !== "object" || value === null || Array.isArray(value)) {
        (this.config as Record<string, unknown>)[algorithm] = value;
        continue;
      }
      const current = (this.config as Record<string, unknown>)[algorithm];
      if (typeof current !== "object" || current === null || Array.isArray(current)) {
        (this.config as Record<string, unknown>)[algorithm] = value;
        continue;
      }
      Object.assign(current, value);
    }
  }
}

export function installAudioMockHandlers(server: AxtpServer, state = new AudioMockState()): AudioMockState {
  state.install(server);
  return state;
}
`;
}

function nodeMain(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
import { AxtpServer } from "@axtp/runtime";
import { NodeTcpServerTransport } from "@axtp/runtime/node";
import { installAudioMockHandlers } from "./audioHandlers.js";

const host = process.env.AXTP_MOCK_TCP_HOST ?? "127.0.0.1";
const port = Number.parseInt(process.env.AXTP_MOCK_TCP_PORT ?? "50362", 10);
const transport = new NodeTcpServerTransport({ host, port });
const server = new AxtpServer(transport, { logicalRole: "server" });
installAudioMockHandlers(server);
await server.listen();

console.log(\`AXTP TCP mock server listening on \${host}:\${transport.boundPort ?? port}\`);

let shutdownPromise: Promise<void> | undefined;
function shutdown(): Promise<void> {
  shutdownPromise ??= server.close().catch((error: unknown) => {
    console.error("AXTP TCP mock server shutdown failed", error);
    process.exitCode = 1;
  });
  return shutdownPromise;
}

process.once("SIGINT", () => {
  void shutdown().finally(() => process.exit(process.exitCode ?? 0));
});
process.once("SIGTERM", () => {
  void shutdown().finally(() => process.exit(process.exitCode ?? 0));
});
`;
}

function nodeSmoke(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
import assert from "node:assert/strict";
import {
  AxtpError,
  AxtpClient,
  AxtpServer,
  ErrorCode
} from "@axtp/runtime";
import { NodeTcpClientTransport, NodeTcpServerTransport } from "@axtp/runtime/node";
import { installAudioMockHandlers } from "./audioHandlers.js";

let server: AxtpServer | undefined;
let client: AxtpClient | undefined;

try {
  const serverTransport = new NodeTcpServerTransport({ host: "127.0.0.1", port: 0 });
  server = new AxtpServer(serverTransport, { logicalRole: "server" });
  installAudioMockHandlers(server);
  await server.listen();

  const port = serverTransport.boundPort;
  assert.notEqual(port, undefined);
  client = new AxtpClient(
    new NodeTcpClientTransport({ host: "127.0.0.1", port: port as number }),
    { logicalRole: "client", defaultTimeoutMs: 500 }
  );
  await client.connect(500);
  assert.equal(client.isReady, true);
  assert.notEqual(client.sid, "");

  const response = await client.callRaw("audio.getAlgorithmConfig", {}) as {
    noiseSuppression: { enabled: boolean };
  };
  assert.equal(response.noiseSuppression.enabled, true);

  await assert.rejects(
    client.callRaw("vendor.missing", {}),
    (error: unknown) => error instanceof AxtpError && error.code === ErrorCode.RpcMethodNotFound
  );
  await assert.rejects(
    client.callRaw("audio.resetAlgorithmConfig", {}),
    (error: unknown) => error instanceof AxtpError && error.code === ErrorCode.NotSupported
  );

  const liveResponse = await client.callRaw("audio.getAlgorithmCapabilities", {}) as {
    capability: string;
  };
  assert.equal(liveResponse.capability, "audio.algorithm");
  assert.equal(client.isReady, true);
  console.log(JSON.stringify(liveResponse));
} finally {
  try {
    if (client !== undefined) await client.close();
  } finally {
    if (server !== undefined) await server.close();
  }
}
`;
}

async function emitCppMockServer(dir: string): Promise<void> {
  await Promise.all([
    writeTextFile(path.join(dir, "CMakeLists.txt"), `cmake_minimum_required(VERSION 3.16)

project(axtp_generated_cpp_mock_server LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(AXTP_CPP_RUNTIME_DIR "\${CMAKE_CURRENT_LIST_DIR}/../../../axtp-cpp-runtime" CACHE PATH "Path to axtp-cpp-runtime")

if(NOT TARGET axtp::sdk)
  add_subdirectory("\${AXTP_CPP_RUNTIME_DIR}" "\${CMAKE_BINARY_DIR}/axtp-cpp-runtime")
endif()

add_library(axtp_cpp_mock_handlers INTERFACE)
target_include_directories(axtp_cpp_mock_handlers INTERFACE "\${CMAKE_CURRENT_LIST_DIR}/include")
target_link_libraries(axtp_cpp_mock_handlers INTERFACE axtp::sdk)

add_executable(axtp_cpp_mock_server src/main.cpp)
target_link_libraries(axtp_cpp_mock_server PRIVATE axtp_cpp_mock_handlers)

enable_testing()
add_executable(axtp_cpp_mock_server_smoke tests/smoke.cpp)
target_link_libraries(axtp_cpp_mock_server_smoke PRIVATE axtp_cpp_mock_handlers)
add_test(NAME axtp_cpp_mock_server_smoke COMMAND axtp_cpp_mock_server_smoke)
`),
    writeTextFile(path.join(dir, "README.md"), `# Generated AXTP C++ Mock Scenario Harness

This generated project uses the root CMake project from the sibling
\`axtp-cpp-runtime\` repository and links the \`axtp::sdk\` target. It runs
generated mock scenario handlers on top of the C++ runtime server API.

\`\`\`bash
cmake -S . -B build
cmake --build build
ctest --test-dir build --output-on-failure
\`\`\`

Override the runtime location with \`-DAXTP_CPP_RUNTIME_DIR=/path/to/axtp-cpp-runtime\`.
`),
    writeTextFile(path.join(dir, "include/audio_mock_handlers.hpp"), cppAudioHandlers()),
    writeTextFile(path.join(dir, "src/main.cpp"), cppMain()),
    writeTextFile(path.join(dir, "tests/smoke.cpp"), cppSmoke())
  ]);
}

function cppAudioHandlers(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
#pragma once

#include <exception>
#include <nlohmann/json.hpp>
#include <string>
#include <string_view>

#include <axtp_sdk.hpp>

namespace axtp::mock {

class AudioMockState {
public:
    AudioMockState()
        : _config(defaultConfig()) {}

    void install(sdk::AxtpServer& server) {
        server.onJson("audio.getAlgorithmConfig",
                      [this](const RpcContext&, std::string_view) { return configJson(); });
        server.onJson("audio.getAlgorithmCapabilities",
                      [](const RpcContext&, std::string_view) { return capabilitiesJson(); });
        server.onJson("audio.setAlgorithmConfig",
                      [this](const RpcContext&, std::string_view params) {
                          return setAlgorithmConfig(params);
                      });
    }

    std::string configJson() const {
        return _config.dump();
    }

    std::string setAlgorithmConfig(std::string_view params) {
        try {
            const auto parsed = nlohmann::json::parse(params.begin(), params.end());
            if (parsed.is_object()) {
                if (const auto config = parsed.find("config");
                    config != parsed.end() && config->is_object()) {
                    mergeConfig(*config);
                } else {
                    mergeConfig(parsed);
                }
            }
        } catch (const std::exception&) {
        }
        auto response = nlohmann::json::object();
        response["applyState"] = "applied";
        response["requiresAudioRestart"] = false;
        response["config"] = _config;
        return response.dump();
    }

private:
    static nlohmann::json defaultConfig() {
        auto noiseSuppression = nlohmann::json::object();
        noiseSuppression["enabled"] = true;
        noiseSuppression["level"] = 1;

        auto echoCancellation = nlohmann::json::object();
        echoCancellation["enabled"] = true;
        echoCancellation["nlpLevel"] = 1;

        auto config = nlohmann::json::object();
        config["noiseSuppression"] = std::move(noiseSuppression);
        config["echoCancellation"] = std::move(echoCancellation);
        return config;
    }

    static std::string capabilitiesJson() {
        auto enabled = nlohmann::json::object();
        enabled["type"] = "boolean";
        enabled["defaultBoolean"] = true;

        auto level = nlohmann::json::object();
        level["type"] = "uint8";
        level["min"] = 0;
        level["max"] = 5;
        level["step"] = 1;
        level["defaultUInt8"] = 1;

        auto noiseSuppression = nlohmann::json::object();
        noiseSuppression["supported"] = true;
        noiseSuppression["enabled"] = enabled;
        noiseSuppression["level"] = level;

        auto nlpLevel = level;
        nlpLevel["max"] = 3;

        auto echoCancellation = nlohmann::json::object();
        echoCancellation["supported"] = true;
        echoCancellation["enabled"] = enabled;
        echoCancellation["nlpLevel"] = nlpLevel;

        auto algorithms = nlohmann::json::object();
        algorithms["noiseSuppression"] = std::move(noiseSuppression);
        algorithms["echoCancellation"] = std::move(echoCancellation);

        auto updatePolicy = nlohmann::json::object();
        updatePolicy["partialUpdateSupported"] = true;
        updatePolicy["multiAlgorithmUpdateSupported"] = true;
        updatePolicy["atomicUpdateSupported"] = true;

        auto response = nlohmann::json::object();
        response["capability"] = "audio.algorithm";
        response["updatePolicy"] = std::move(updatePolicy);
        response["algorithms"] = std::move(algorithms);
        return response.dump();
    }

    void mergeConfig(const nlohmann::json& patch) {
        for (auto algorithm = patch.begin(); algorithm != patch.end(); ++algorithm) {
            if (!algorithm.value().is_object()) {
                _config[algorithm.key()] = algorithm.value();
                continue;
            }
            auto currentValue = _config.find(algorithm.key());
            if (currentValue == _config.end() || !currentValue->is_object()) {
                _config[algorithm.key()] = algorithm.value();
                continue;
            }
            for (auto field = algorithm.value().begin(); field != algorithm.value().end(); ++field) {
                (*currentValue)[field.key()] = field.value();
            }
        }
    }

    nlohmann::json _config;
};

inline void installAudioMockHandlers(sdk::AxtpServer& server, AudioMockState& state) {
    state.install(server);
}

}  // namespace axtp::mock
`;
}

function cppMain(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
#include <iostream>
#include <memory>

#include "audio_mock_handlers.hpp"
#include <core/runtime/testing/mock_transport.hpp>

int main() {
    axtp::sdk::AxtpServer server;
    axtp::mock::AudioMockState state;
    axtp::mock::installAudioMockHandlers(server, state);
    server.attachTransport(std::make_unique<axtp::MockTransport>());
    std::cout << "AXTP C++ mock scenario harness initialized with MockTransport.\\n";
    return 0;
}
`;
}

function cppSmoke(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
#include <cassert>
#include <string>

#include "audio_mock_handlers.hpp"

int main() {
    axtp::sdk::AxtpServer server;
    axtp::mock::AudioMockState state;
    axtp::mock::installAudioMockHandlers(server, state);
    const auto response = state.setAlgorithmConfig("{\\"config\\":{\\"noiseSuppression\\":{\\"level\\":2}}}");
    assert(response.find("\\"applyState\\":\\"applied\\"") != std::string::npos);
    assert(state.configJson().find("\\"level\\":2") != std::string::npos);
    return 0;
}
`;
}
