import path from "node:path";
import type { SpecModel } from "../models.js";
import { toJsonStable, writeTextFile } from "../util.js";

const audioConfig = {
  noiseSuppression: { enabled: true, level: 1 },
  echoCancellation: { enabled: true, nlpLevel: 1 }
};

const audioCapabilities = {
  capability: "audio.algorithm",
  updatePolicy: {
    partialUpdateSupported: true,
    multiAlgorithmUpdateSupported: true,
    atomicUpdateSupported: true
  },
  algorithms: {
    noiseSuppression: {
      supported: true,
      enabled: { type: "boolean", defaultBoolean: true },
      level: { type: "uint8", min: 0, max: 5, step: 1, defaultUInt8: 1 }
    },
    echoCancellation: {
      supported: true,
      enabled: { type: "boolean", defaultBoolean: true },
      nlpLevel: { type: "uint8", min: 0, max: 3, step: 1, defaultUInt8: 1 }
    }
  }
};

export async function emitMockServerFiles(spec: SpecModel, generatedDir: string): Promise<void> {
  await Promise.all([
    emitSharedFixtures(spec, path.join(generatedDir, "shared")),
    emitNodeMockServer(path.join(generatedDir, "node-mock-server")),
    emitCppMockServer(path.join(generatedDir, "cpp-mock-server"))
  ]);
}

async function emitSharedFixtures(spec: SpecModel, dir: string): Promise<void> {
  const audioMethods = spec.methods
    .filter((method) => method.domain === "audio")
    .sort((lhs, rhs) => lhs.id - rhs.id)
    .map((method) => ({
      id: method.id,
      name: method.name,
      requestSchema: method.requestSchema,
      responseSchema: method.responseSchema
    }));
  await Promise.all([
    writeTextFile(path.join(dir, "audio-scenario.json"), toJsonStable({
      name: "audio-default",
      description: "Default AXTP audio mock responses for client-side protocol testing.",
      methods: {
        "audio.getAlgorithmConfig": { response: audioConfig },
        "audio.getAlgorithmCapabilities": { response: audioCapabilities },
        "audio.setAlgorithmConfig": {
          response: {
            applyState: "applied",
            requiresAudioRestart: false,
            config: audioConfig
          }
        }
      }
    })),
    writeTextFile(path.join(dir, "audio-registry.json"), toJsonStable({ methods: audioMethods }))
  ]);
}

async function emitNodeMockServer(dir: string): Promise<void> {
  await Promise.all([
    writeTextFile(path.join(dir, "package.json"), `{
  "name": "@axtp/generated-node-mock-server",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "smoke": "node dist/smoke.js",
    "test": "node dist/smoke.js"
  },
  "dependencies": {
    "@axtp/runtime": "link:../../../axtp-node-runtime"
  },
  "devDependencies": {
    "@types/node": "^22.10.2",
    "typescript": "^5.7.2"
  },
  "packageManager": "pnpm@11.3.0"
}
`),
    writeTextFile(path.join(dir, "tsconfig.json"), `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`),
    writeTextFile(path.join(dir, "README.md"), `# Generated AXTP Node Mock Server

This generated project uses \`@axtp/runtime\` from the sibling
\`axtp-node-runtime\` repository.

\`\`\`bash
pnpm install
pnpm build
pnpm smoke
\`\`\`

The default handlers cover \`audio.getAlgorithmConfig\`,
\`audio.getAlgorithmCapabilities\`, and \`audio.setAlgorithmConfig\`.
`),
    writeTextFile(path.join(dir, "src/audioHandlers.ts"), nodeAudioHandlers()),
    writeTextFile(path.join(dir, "src/main.ts"), nodeMain()),
    writeTextFile(path.join(dir, "src/smoke.ts"), nodeSmoke())
  ]);
}

function nodeAudioHandlers(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
import type { AxtpServer, JsonRpcHandler } from "@axtp/runtime";

const defaultConfig = {
  noiseSuppression: { enabled: true, level: 1 },
  echoCancellation: { enabled: true, nlpLevel: 1 }
};

const capabilities = ${JSON.stringify(audioCapabilities, null, 2)};

export class AudioMockState {
  private config = structuredClone(defaultConfig);

  install(server: AxtpServer): void {
    server.onJson("audio.getAlgorithmConfig", this.getAlgorithmConfig);
    server.onJson("audio.getAlgorithmCapabilities", this.getAlgorithmCapabilities);
    server.onJson("audio.setAlgorithmConfig", this.setAlgorithmConfig);
  }

  private readonly getAlgorithmConfig: JsonRpcHandler = async () => JSON.stringify(this.config);

  private readonly getAlgorithmCapabilities: JsonRpcHandler = async () => JSON.stringify(capabilities);

  private readonly setAlgorithmConfig: JsonRpcHandler = async (_context, paramsJson) => {
    try {
      const parsed = paramsJson.length > 0 ? JSON.parse(paramsJson) : {};
      const patch = typeof parsed.config === "object" && parsed.config !== null ? parsed.config : parsed;
      this.mergeConfig(patch);
    } catch {
      // Invalid client JSON keeps the previous mock state and still returns a deterministic response.
    }
    return JSON.stringify({
      applyState: "applied",
      requiresAudioRestart: false,
      config: this.config
    });
  };

  private mergeConfig(patch: unknown): void {
    if (typeof patch !== "object" || patch === null) return;
    for (const [algorithm, value] of Object.entries(patch as Record<string, unknown>)) {
      if (typeof value !== "object" || value === null || Array.isArray(value)) {
        (this.config as Record<string, unknown>)[algorithm] = value;
        continue;
      }
      const current = (this.config as Record<string, unknown>)[algorithm];
      if (typeof current !== "object" || current === null || Array.isArray(current)) {
        (this.config as Record<string, unknown>)[algorithm] = value;
        continue;
      }
      Object.assign(current, value);
    }
  }
}

export function installAudioMockHandlers(server: AxtpServer, state = new AudioMockState()): AudioMockState {
  state.install(server);
  return state;
}
`;
}

function nodeMain(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
import { AxtpServer, MockTransport } from "@axtp/runtime";
import { installAudioMockHandlers } from "./audioHandlers.js";

const server = new AxtpServer();
await server.attachTransport(new MockTransport());
installAudioMockHandlers(server);

console.log("AXTP Node mock server initialized with MockTransport.");
console.log("Use src/smoke.ts as an executable in-process client/server example.");
`;
}

function nodeSmoke(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
import assert from "node:assert/strict";
import { AxtpClient, AxtpServer, MockTransport } from "@axtp/runtime";
import { installAudioMockHandlers } from "./audioHandlers.js";

const client = new AxtpClient({ timeoutMs: 200 });
const server = new AxtpServer();
const clientTransport = new MockTransport();
const serverTransport = new MockTransport();

await client.attachTransport(clientTransport);
await server.attachTransport(serverTransport);
installAudioMockHandlers(server);

function bridge(left: MockTransport, right: MockTransport): void {
  while (true) {
    const chunk = left.tryPopOutgoing();
    if (chunk === undefined) return;
    right.injectIncoming(chunk);
  }
}

const pump = setInterval(async () => {
  bridge(clientTransport, serverTransport);
  await server.poll();
  bridge(serverTransport, clientTransport);
  await client.poll();
}, 0);

try {
  const response = await client.callJson("audio.getAlgorithmConfig", "{}");
  assert.equal(JSON.parse(response).noiseSuppression.enabled, true);
  console.log(response);
} finally {
  clearInterval(pump);
  await client.close();
  await server.close();
}
`;
}

async function emitCppMockServer(dir: string): Promise<void> {
  await Promise.all([
    writeTextFile(path.join(dir, "CMakeLists.txt"), `cmake_minimum_required(VERSION 3.16)

project(axtp_generated_cpp_mock_server LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(AXTP_CPP_RUNTIME_DIR "\${CMAKE_CURRENT_LIST_DIR}/../../../axtp-cpp-runtime" CACHE PATH "Path to axtp-cpp-runtime")

if(NOT TARGET axtp_sdk)
  add_subdirectory("\${AXTP_CPP_RUNTIME_DIR}/sdk" "\${CMAKE_BINARY_DIR}/axtp-cpp-sdk")
endif()

add_library(axtp_cpp_mock_handlers INTERFACE)
target_include_directories(axtp_cpp_mock_handlers INTERFACE "\${CMAKE_CURRENT_LIST_DIR}/include")
target_link_libraries(axtp_cpp_mock_handlers INTERFACE axtp_sdk)

add_executable(axtp_cpp_mock_server src/main.cpp)
target_link_libraries(axtp_cpp_mock_server PRIVATE axtp_cpp_mock_handlers)

enable_testing()
add_executable(axtp_cpp_mock_server_smoke tests/smoke.cpp)
target_link_libraries(axtp_cpp_mock_server_smoke PRIVATE axtp_cpp_mock_handlers)
add_test(NAME axtp_cpp_mock_server_smoke COMMAND axtp_cpp_mock_server_smoke)
`),
    writeTextFile(path.join(dir, "README.md"), `# Generated AXTP C++ Mock Server

This generated project uses \`axtp-cpp-runtime\` from a sibling repository.

\`\`\`bash
cmake -S . -B build
cmake --build build
ctest --test-dir build --output-on-failure
\`\`\`

Override the runtime location with \`-DAXTP_CPP_RUNTIME_DIR=/path/to/axtp-cpp-runtime\`.
`),
    writeTextFile(path.join(dir, "include/audio_mock_handlers.hpp"), cppAudioHandlers()),
    writeTextFile(path.join(dir, "src/main.cpp"), cppMain()),
    writeTextFile(path.join(dir, "tests/smoke.cpp"), cppSmoke())
  ]);
}

function cppAudioHandlers(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
#pragma once

#include <boost/json.hpp>
#include <string>
#include <string_view>

#include "axtp_sdk_all.hpp"

namespace axtp::mock {

class AudioMockState {
public:
    AudioMockState()
        : _config(defaultConfig()) {}

    void install(sdk::AxtpServer& server) {
        server.onJson("audio.getAlgorithmConfig",
                      [this](const RpcContext&, std::string_view) { return configJson(); });
        server.onJson("audio.getAlgorithmCapabilities",
                      [](const RpcContext&, std::string_view) { return capabilitiesJson(); });
        server.onJson("audio.setAlgorithmConfig",
                      [this](const RpcContext&, std::string_view params) {
                          return setAlgorithmConfig(params);
                      });
    }

    std::string configJson() const {
        return boost::json::serialize(_config);
    }

    std::string setAlgorithmConfig(std::string_view params) {
        try {
            const auto parsed = boost::json::parse(params);
            if (parsed.is_object()) {
                const auto& root = parsed.as_object();
                if (const auto* config = root.if_contains("config");
                    config != nullptr && config->is_object()) {
                    mergeConfig(config->as_object());
                } else {
                    mergeConfig(root);
                }
            }
        } catch (const std::exception&) {
        }
        boost::json::object response;
        response["applyState"] = "applied";
        response["requiresAudioRestart"] = false;
        response["config"] = _config;
        return boost::json::serialize(response);
    }

private:
    static boost::json::object defaultConfig() {
        boost::json::object noiseSuppression;
        noiseSuppression["enabled"] = true;
        noiseSuppression["level"] = 1;

        boost::json::object echoCancellation;
        echoCancellation["enabled"] = true;
        echoCancellation["nlpLevel"] = 1;

        boost::json::object config;
        config["noiseSuppression"] = std::move(noiseSuppression);
        config["echoCancellation"] = std::move(echoCancellation);
        return config;
    }

    static std::string capabilitiesJson() {
        boost::json::object enabled;
        enabled["type"] = "boolean";
        enabled["defaultBoolean"] = true;

        boost::json::object level;
        level["type"] = "uint8";
        level["min"] = 0;
        level["max"] = 5;
        level["step"] = 1;
        level["defaultUInt8"] = 1;

        boost::json::object noiseSuppression;
        noiseSuppression["supported"] = true;
        noiseSuppression["enabled"] = enabled;
        noiseSuppression["level"] = level;

        boost::json::object nlpLevel = level;
        nlpLevel["max"] = 3;

        boost::json::object echoCancellation;
        echoCancellation["supported"] = true;
        echoCancellation["enabled"] = enabled;
        echoCancellation["nlpLevel"] = nlpLevel;

        boost::json::object algorithms;
        algorithms["noiseSuppression"] = std::move(noiseSuppression);
        algorithms["echoCancellation"] = std::move(echoCancellation);

        boost::json::object updatePolicy;
        updatePolicy["partialUpdateSupported"] = true;
        updatePolicy["multiAlgorithmUpdateSupported"] = true;
        updatePolicy["atomicUpdateSupported"] = true;

        boost::json::object response;
        response["capability"] = "audio.algorithm";
        response["updatePolicy"] = std::move(updatePolicy);
        response["algorithms"] = std::move(algorithms);
        return boost::json::serialize(response);
    }

    void mergeConfig(const boost::json::object& patch) {
        for (const auto& algorithm : patch) {
            if (!algorithm.value().is_object()) {
                _config[algorithm.key()] = algorithm.value();
                continue;
            }
            auto* currentValue = _config.if_contains(algorithm.key());
            if (currentValue == nullptr || !currentValue->is_object()) {
                _config[algorithm.key()] = algorithm.value();
                continue;
            }
            auto& current = currentValue->as_object();
            for (const auto& field : algorithm.value().as_object()) {
                current[field.key()] = field.value();
            }
        }
    }

    boost::json::object _config;
};

inline void installAudioMockHandlers(sdk::AxtpServer& server, AudioMockState& state) {
    state.install(server);
}

}  // namespace axtp::mock
`;
}

function cppMain(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
#include <iostream>
#include <memory>

#include "audio_mock_handlers.hpp"
#include "testing/mock_transport.hpp"

int main() {
    axtp::sdk::AxtpServer server;
    axtp::mock::AudioMockState state;
    axtp::mock::installAudioMockHandlers(server, state);
    server.attachTransport(std::make_unique<axtp::MockTransport>());
    std::cout << "AXTP C++ mock server initialized with MockTransport.\\n";
    return 0;
}
`;
}

function cppSmoke(): string {
  return `// Generated by axtp-mock-server generator. Do not edit manually.
#include <cassert>
#include <string>

#include "audio_mock_handlers.hpp"

int main() {
    axtp::sdk::AxtpServer server;
    axtp::mock::AudioMockState state;
    axtp::mock::installAudioMockHandlers(server, state);
    const auto response = state.setAlgorithmConfig("{\\"config\\":{\\"noiseSuppression\\":{\\"level\\":2}}}");
    assert(response.find("\\"applyState\\":\\"applied\\"") != std::string::npos);
    assert(state.configJson().find("\\"level\\":2") != std::string::npos);
    return 0;
}
`;
}
